spring.application.name=springbookDemo
spring.profiles.active=dev

server.port=8080
server.servlet.session.timeout=2h

app.upload.dir=${APP_UPLOAD_DIR:./uploads}
app.upload.max-size=500MB

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=edu.neusoft.springbookdemo.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

logging.level.edu.neusoft.springbookdemo=debug
